[project]
name = "admin-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.122.0",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]
